{{- if .Values.app.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "cgs.fullname" . }}
  labels:
    {{- include "cgs.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cgs.fullname" . }}
  minReplicas: {{ .Values.app.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.app.autoscaling.maxReplicas }}
  behavior:
    {{- toYaml .Values.app.autoscaling.behavior | nindent 4 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.app.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.app.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
{{- if .Values.ml.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "cgs.fullname" . }}-ml
  labels:
    {{- include "cgs.labels" . | nindent 4 }}
    app.kubernetes.io/component: ml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cgs.fullname" . }}-ml
  minReplicas: {{ .Values.ml.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.ml.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.ml.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- if .Values.soar.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "cgs.fullname" . }}-soar
  labels:
    {{- include "cgs.labels" . | nindent 4 }}
    app.kubernetes.io/component: soar
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cgs.fullname" . }}-soar
  minReplicas: {{ .Values.soar.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.soar.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.soar.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
